p = input('escreva algo: ')
print('O tipo primitivo é {}'.format(type(p)))
print('tem espaços? {}'.format(p.isspace()))
print('É um número? {}'.format(p.isnumeric()))
print('É alfabético? {}'.format(p.isalpha()))
print('É alfanumérico? {}'.format(p.isalnum()))
print('Está em maúisculas? {}'.format(p.isupper()))
print('Está em minúsculas? {}'.format(p.islower()))
print('Está capitalizada? {}'.format(p.istitle()))